
PREFIX j: <http://release.niem.gov/niem/domains/jxdm/7.2/#>
PREFIX nc: <http://release.niem.gov/niem/niem-core/5.0/#>

SELECT ?case ?start_date 
       (MIN(?date) AS ?filing_date_first) 
       ?end_date 
       (MAX(?date) AS ?filing_date_last)
       (GROUP_CONCAT(?type; separator=" ") AS ?types)
       (GROUP_CONCAT(?duration; separator=" ") AS ?durations)
       
WHERE {
  VALUES ?case {<http://schemas.scales-okn.org/rdf/scales#Case/ga-clayton-state-civil;;0:23-cv-00536> <http://schemas.scales-okn.org/rdf/scales#Case/ga-clayton-state-civil;;0:23-cv-02245> <http://schemas.scales-okn.org/rdf/scales#Case/ga-clayton-state;;0:23-cr-01253> <http://schemas.scales-okn.org/rdf/scales#Case/ga-clayton-state;;0:23-cr-03289>}

  OPTIONAL { ?case nc:StartDate ?start_date . }
  OPTIONAL { ?case nc:EndDate ?end_date . }

  ?case j:RegisterAction ?entry .
  ?entry j:RegisterActionDate ?date .

  OPTIONAL {
    ?entry j:Sentence ?sentence .
    ?sentence j:SentenceDescriptionText ?type .
    ?sentence j:SentenceTerm ?term .
    ?term j:TermDuration ?duration .
  }
}
GROUP BY ?case ?start_date ?end_date
