
PREFIX j: <http://release.niem.gov/niem/domains/jxdm/7.2/#>
PREFIX nc: <http://release.niem.gov/niem/niem-core/5.0/#>
PREFIX scales: <http://schemas.scales-okn.org/rdf/scales#>

SELECT ?case ?label ?nos ?court
WHERE { 
    ?case scales:OntologyLabel ?label ;
        j:CaseCourt ?court .
    OPTIONAL { ?case nc:CaseSubCategoryText ?nos . }
}
